// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2YIFR4WYEbMPVttJJdxHSv9lzw3kwZ6g',
    appId: '1:367599712427:web:0782fdf6e490f50fdd9fee',
    messagingSenderId: '367599712427',
    projectId: 'first-app-4ab4d',
    authDomain: 'first-app-4ab4d.firebaseapp.com',
    storageBucket: 'first-app-4ab4d.firebasestorage.app',
    measurementId: 'G-Y7PRH47RZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlVRIwao3xgTmYiXQV-Yb1ft00eemy6Q',
    appId: '1:367599712427:android:6d0ffc3d159b15c2dd9fee',
    messagingSenderId: '367599712427',
    projectId: 'first-app-4ab4d',
    storageBucket: 'first-app-4ab4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFFEcfKnYGr081KG41Wl2QUgDxJlkjYbA',
    appId: '1:367599712427:ios:acf8dfc21dec5c87dd9fee',
    messagingSenderId: '367599712427',
    projectId: 'first-app-4ab4d',
    storageBucket: 'first-app-4ab4d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFFEcfKnYGr081KG41Wl2QUgDxJlkjYbA',
    appId: '1:367599712427:ios:acf8dfc21dec5c87dd9fee',
    messagingSenderId: '367599712427',
    projectId: 'first-app-4ab4d',
    storageBucket: 'first-app-4ab4d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2YIFR4WYEbMPVttJJdxHSv9lzw3kwZ6g',
    appId: '1:367599712427:web:ef25bc5e4962cd7add9fee',
    messagingSenderId: '367599712427',
    projectId: 'first-app-4ab4d',
    authDomain: 'first-app-4ab4d.firebaseapp.com',
    storageBucket: 'first-app-4ab4d.firebasestorage.app',
    measurementId: 'G-HYKSQYTP4N',
  );

}